---
title: "Acknowledgements"
description: |
   Thank You
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

This workshop has been given multiple times. This workshop was partially funded with a NLM T15 Training Grant supplement for Data Science: T15-LM007088-23

Thank you to PDX-R for hosting the workshop multiple times.

Thank you to Jessica Minnier who contributed and taught this workshop with me for WNAR2019.

Thank you to BioData Club for the latest version of the workshop, including our TAs:

- Pierrette Lo
- Dar'ya Pozhidayeva
- Eric Leung
- Marijane White
- Eric Earl

Special Thanks to both Pierrette and Dar'ya for sharing their experiences and stumbling blocks about learning Shiny - they definitely helped me to reformulate how to teach Shiny and focus on the basics.

Thank you to Vivian Peng, for inspiring the layout for the slides.

Slides done in [`{xaringan}`](https://bookdown.org/yihui/rmarkdown/xaringan.html) with [`{flair}`](https://github.com/r-for-educators/flair) and [`{xaringanExtra}`](https://github.com/gadenbuie/xaringanExtra).

Site done with [`{distill}`](https://rstudio.github.io/distill/).

# Licensing Information

Copyright 2021 Ted Laderas and Jessica Minnier

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
